#!/bin/bash

battery_status () {
    old_ifs=$IFS
    IFS=";"
    read -ra fullstatus <<< "$(pmset -g batt | sed 'N;s/\n/;/' | sed 's/\t/;/g' | awk -F\ present '{print $1}' | sed 's/; /;/g')"
    IFS=$old_ifs

    source_line=${fullstatus[0]}
    perc=${fullstatus[2]//[^0-9]}
    third_val=${fullstatus[3]}
    fourth_val=${fullstatus[4]}

    remaining=''
    symbol='•'
    source=''

    if [[ $source_line =~ 'AC Power' ]]; then
        source='⏦' # 🔌
    elif [[ $source_line =~ 'Battery Power' ]]; then
        source='⎓' # 🔋
    fi

    if [[ $third_val == "AC attached" ]] && [[ $fourth_val == "not charging" ]]; then
        status_color='yellow'
        symbol='Ⅱ'
    elif [ $third_val == "charged" ]; then
        status_color='green,bright'
    elif [ $third_val == "charging" ]; then
        status_color='#ff8000' # orange
        remaining=${fourth_val//[^0-9:]}
    else # [ $third_val == "discharging" ]; then
        status_color='black,bright'
        remaining=${fourth_val//[^0-9:]}
    fi

    if [ $perc -le 5 ]; then
        blink_file="/tmp/.tmux-battery-status-blinker"
        blink=""
        if [[ -e $blink_file ]]; then
          blink=",reverse"
          rm $blink_file
        else
          touch $blink_file
        fi

        perc_color="red$blink"
    elif [ $perc -le 10 ]; then
        perc_color="red,reverse"
    elif [ $perc -le 25 ]; then
        perc_color="#ff8000"
    elif [ $perc -le 50 ]; then
        perc_color="yellow"
    else
        perc_color="green"
    fi

    if [ $perc -le 5 ]; then
        warning="#[fg=red]⚠️  "
    fi

    if [[ $remaining != '' ]]; then
        remaining=" ($remaining)"
    fi

    echo -n "#[fg=default,bold]$source #[fg=$status_color]$symbol #[fg=$perc_color,nobright]$warning${perc}%$remaining"
}

DELIMITER="#[fg=#500000]|"

dnd_status () {
    defaults read com.apple.controlcenter "NSStatusItem Visible DoNotDisturb" | grep -q 1 && echo -n " $DELIMITER #[fg=blue,bright]DnD"
}

echo -n "$DELIMITER #[fg=default]"
echo -n "$(sysctl -n vm.loadavg | cut -f 2,3,4 -d\ ) "
echo -n "$DELIMITER "
battery_status
dnd_status
echo
