#!/bin/bash

battery_status () {
    old_ifs=$IFS
    IFS=';'
    read -ra fullstatus <<< "$(pmset -g batt | tail -n 1 | awk -F\t '{print $2}' | awk -F\ present '{print $1}' | sed 's/; /;/g')"
    IFS=$old_ifs

    perc=${fullstatus[0]//[^0-9]}
    second_val=${fullstatus[1]}
    third_val=${fullstatus[2]}

    remaining=''

    if [[ $second_val == "AC attached" ]] && [[ $third_val == "not charging" ]]; then
        status_color='yellow'
    elif [ $second_val == "charged" ]; then
        status_color='green,bright'
    elif [ $second_val == "charging" ]; then
        status_color='#ff8000' # orange
        remaining=${fullstatus[2]//[^0-9:]}
    else # [ $second_val == "discharging" ]; then
        status_color='black,bright'
        remaining=${fullstatus[2]//[^0-9:]}
    fi

    if [ $perc -le 5 ]; then
        blink_file="/tmp/.tmux-battery-status-blinker"
        blink=""
        if [[ -e $blink_file ]]; then
          blink=",reverse"
          rm $blink_file
        else
          touch $blink_file
        fi

        perc_color="red$blink"
    elif [ $perc -le 10 ]; then
        perc_color="red,reverse"
    elif [ $perc -le 25 ]; then
        perc_color="#ff8000"
    elif [ $perc -le 50 ]; then
        perc_color="yellow"
    else
        perc_color="green"
    fi

    if [ $perc -le 5 ]; then
        warning="#[fg=red]⚠️  "
    fi

    if [[ $remaining != '' ]]; then
        remaining=" ($remaining)"
    fi

    echo -n "#[fg=$status_color]• #[fg=$perc_color,nobright]$warning${perc}%$remaining"
}

DELIMITER="#[fg=#500000]|"

dnd_status () {
    defaults read com.apple.controlcenter "NSStatusItem Visible DoNotDisturb" | grep -q 1 && echo -n " $DELIMITER #[fg=blue,bright]DnD"
}

echo -n "$DELIMITER #[fg=default]"
echo -n "$(sysctl -n vm.loadavg | cut -f 2,3,4 -d\ ) "
echo -n "$DELIMITER "
battery_status
dnd_status
echo
