#!/usr/bin/env python3

import json
import os
import subprocess

if __name__ == '__main__':
    base_instances = []
    instances = []

    p = subprocess.run(['vmrun', 'list'], capture_output=True)
    for l in p.stdout.splitlines():
        l = l.decode('utf-8')
        if l.startswith('Total running VMs:'):
            continue

        vmx = os.path.basename(l)
        hname = os.path.splitext(vmx)[0]

        if hname.startswith('_'):
            base_instances.append(hname[1:])
        else:
            instances.append(hname)

    print(json.dumps({
        '_meta': {},
        'base_instances': base_instances,
        'instances': instances
    }))
